server:
  port: 9020

spring:
  application:
    name: playings-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: playingsDB
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      healthcheck:
        enabled: true
  instance:
    prefer-ip-address: true